spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: postgres
    password: stockpass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: